### PR TITLE
Add GUID to REST API post output for Disqus identification on sheer pages

### PR DESCRIPTION
**Pull request by kurtw**
@rosskarchner 
@Scotchester

### CODE REVIEW

**Comment by Scotchester** [comment]
:rotating_light: n00b alert

What's the difference between the GUID and the ID? And why isn't ID good enough for Disquis identification?

**Comment by kurtw** [comment]
So the GUID is created when the post is saved to the database. If a post is created on content.cf.gov then the GUID would be something like `http://content.cf.gov/?p=7234`. The Disqus plugin that we have uses the post's ID and GUID to uniquely identify a post to serve that posts' comments. Since we were using that for a while (presumably for the life of Disqus integration), we need to be able to get both in elasticsearch to maintain the comments from the old blog posts on the new site.

**Comment by kurtw** [comment]
As for why it's not good enough, it's possible that it's due to RAMP. Not entirely sure.

**Comment by Scotchester** [comment]
Yeah. RAMP doesn't maintain regular IDs from Content to Production.

**Comment by Scotchester** [comment]
:+1:

**Pull request merged**
